# -*- coding: utf-8 -*-
"""SIC Satria Data 2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zNdUecl3k9rFD9E48Y8jfM9SidNtWEqm
"""

import geopandas as gpd
import matplotlib.pyplot as plt
import pandas as pd
import matplotlib.patches as mpatches

# 1. Load peta batas provinsi Indonesia (pastikan path dan filenya sudah benar)
gdf = gpd.read_file('38 Provinsi Indonesia - Provinsi.json')  # Ganti dengan file geojson/shp kamu
gdf

gdf34 = gpd.read_file('indonesia-map-geojson.json')  # Ganti dengan file geojson/shp kamu
gdf34

# 2. Data IKP yang kamu berikan (bisa dari CSV atau langsung dict)
data_ikp = {
    'Kode Provinsi': [11,12,13,14,15,16,17,18,19,21,31,32,33,34,35,36,51,52,53,61,62,63,64,65,71,72,73,74,75,76,81,82,91,94],
    'Kelompok IKP': [5,6,6,5,6,5,5,6,5,5,6,6,6,6,6,6,6,6,5,5,5,6,6,6,6,6,6,6,6,5,4,4,3,2]
}

df_ikp = pd.DataFrame(data_ikp)

df_ikp

# 3. Merge data IKP dengan GeoDataFrame peta berdasarkan kode provinsi
gdf34 = gdf34.merge(df_ikp, left_on='id', right_on='Kode Provinsi')

# 4. Definisikan warna sesuai klaster
colors = {
    1: '#d73027',  # sangat rentan - merah tua
    2: '#fc8d59',  # rentan - orange
    3: '#fee08b',  # agak rentan - kuning muda
    4: '#d9ef8b',  # agak tahan - hijau muda
    5: '#91cf60',  # tahan - hijau sedang
    6: '#1a9850'   # sangat tahan - hijau tua
}

# 5. Map warna berdasarkan kelompok IKP
gdf34['color'] = gdf34['Kelompok IKP'].map(colors)

# 6. Plot peta
fig, ax = plt.subplots(1, 1, figsize=(12, 14))
gdf34.plot(color=gdf34['color'], edgecolor='black', ax=ax)

# 7. Tambahkan legenda
labels = ['Sangat Rentan', 'Rentan', 'Agak Rentan', 'Agak Tahan', 'Tahan', 'Sangat Tahan']
patches = [mpatches.Patch(color=colors[i], label=f'{i}. {labels[i-1]}') for i in range(1,7)]
plt.legend(handles=patches, title='Kategori IKP', loc='lower left')

# 8. Tambahkan judul
plt.title('Peta Indeks Ketahanan Pangan Indonesia 2024\nBerdasarkan Provinsi dan Kelompok IKP', fontsize=16)

# Hilangkan axis
ax.set_axis_off()

plt.show()

"""# KEPADATAN PENDUDUK"""

import pandas as pd

# Ganti dengan path ke file kamu
file_path = 'kepadatan penduduk - Copy.csv'  # atau .xlsx jika pakai Excel
df = pd.read_csv(file_path)  # kalau Excel: pd.read_excel(file_path)

# Rename kolom untuk kemudahan (opsional)
df = df.rename(columns={'Kepadatan Penduduk per km persegi (Km2)': 'Kepadatan'})

df

# Buat kolom klaster kategori 1–6 berdasarkan kuantil
df['Kategori Kepadatan'] = pd.qcut(df['Kepadatan'], 6, labels=[1, 2, 3, 4, 5, 6]).astype(int)

# Tampilkan hasil
print(df[['Kode Provinsi', 'Provinsi', 'Kepadatan', 'Kategori Kepadatan']])

df.to_csv('kepadatan_klaster.csv', index=False)

read_padat = 'kepadatan_klaster.csv'  # atau .xlsx jika pakai Excel
read_padat = pd.read_csv(read_padat)  # kalau Excel: pd.read_excel(file_path)
df_padat = pd.DataFrame(read_padat)
df_padat

# 3. Merge data IKP dengan GeoDataFrame peta berdasarkan kode provinsi
gdf = gdf.merge(df_padat, left_on='id', right_on='Kode Provinsi')

# 4. Definisikan warna sesuai klaster
colors = {
    1: '#1a9850',  # sangat rentan - merah tua
    2: '#91cf60',  # rentan - orange
    3: '#d9ef8b',  # agak rentan - kuning muda
    4: '#fee08b',  # agak tahan - hijau muda
    5: '#fc8d59',  # tahan - hijau sedang
    6: '#d73027'   # sangat tahan - hijau tua
}

# 5. Map warna berdasarkan kelompok IKP
gdf['color'] = gdf['Kategori Kepadatan'].map(colors)

# 6. Plot peta
fig, ax = plt.subplots(1, 1, figsize=(12, 14))
gdf.plot(color=gdf['color'], edgecolor='white', ax=ax)

# 7. Tambahkan legenda
labels = ['Sangat Padat', 'Padat', 'Agak Padat', 'Agak Kurang Padat', 'Tidak Padat', 'Sangat Tidak Padat']
patches = [mpatches.Patch(color=colors[i], label=f'{i}. {labels[i-1]}') for i in range(1,7)]
plt.legend(handles=patches, title='Kategori IKP', loc='lower left')

# 8. Tambahkan judul
plt.title('Peta Klaster Kepadatan Penduduk per km persegi (Km2) Tahun 2025', fontsize=16)

# Hilangkan axis
ax.set_axis_off()

plt.show()

# 7. Tambahkan legenda
labels = ['Sangat Rentan', 'Rentan', 'Agak Rentan', 'Agak Tahan', 'Tahan', 'Sangat Tahan']
patches = [mpatches.Patch(color=colors[i], label=f'{i}. {labels[i-1]}') for i in range(1,7)]
plt.legend(handles=patches, title='Kategori IKP', loc='lower left')

# 8. Tambahkan judul
plt.title('Peta Indeks Ketahanan Pangan Indonesia 2024\nBerdasarkan Provinsi dan Kelompok IKP', fontsize=16)

# Hilangkan axis
ax.set_axis_off()

plt.show()

# 6. Plot peta
fig, ax = plt.subplots(1, 1, figsize=(12, 14))
gdf.plot(color=gdf['color'], edgecolor='white', ax=ax)

import matplotlib.patches as mpatches

# Ambil rentang kepadatan per kategori dari data hasil merge
ranges = {}
for k in range(1, 7):
    subset = gdf[gdf['Kategori Kepadatan'] == k]['Kepadatan']
    if len(subset) > 0:
        min_val = int(subset.min())
        max_val = int(subset.max())
        if min_val == max_val:
            label_range = f"<{min_val}" if k == 1 else f"{min_val}"
        else:
            # Untuk kategori 1 kalau rentangnya kecil, pakai <max_val supaya lebih informatif
            if k == 1:
                label_range = f"<{max_val+1}"
            else:
                label_range = f"{min_val}-{max_val}"
    else:
        label_range = "N/A"  # jika kategori kosong
    ranges[k] = label_range

# Buat label lengkap untuk legend
labels_with_range = [f"{i}. {ranges[i]}" for i in range(1, 7)]

# Update legend patches dengan label baru
patches = [mpatches.Patch(color=colors[i], label=labels_with_range[i-1]) for i in range(1,7)]

# Ganti bagian legendmu dengan ini:
plt.legend(handles=patches, title='', loc='lower left')

import matplotlib.pyplot as plt

# Data
bulan = ['April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September']
sapi = [140, 142, 145, 147, 149, 150]
ayam = [38, 39, 41, 42, 43, 44]
kambing = [130, 133, 135, 137, 139, 140]
ikan = [45, 46, 48, 47, 49, 50]
bebek = [60, 62, 64, 65, 66, 68]

# Plot
plt.figure(figsize=(10, 6))

plt.plot(bulan, sapi, color='red', linewidth=2.5)
plt.plot(bulan, ayam, color='blue', linewidth=2.5)
plt.plot(bulan, kambing, color='green', linewidth=2.5)
plt.plot(bulan, ikan, color='orange', linewidth=2.5)
plt.plot(bulan, bebek, color='purple', linewidth=2.5)

# Perbesar font
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)

# Hapus judul dan keterangan
plt.title('')
plt.legend([],[], frameon=False)

# Tampilkan plot
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

# Data
bulan = ['April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September']
sapi = [142, 139, 144, 147, 143, 148]
ayam = [40, 42, 41, 39, 43, 45]
kambing = [128, 132, 129, 131, 134, 136]
ikan = [46, 44, 49, 48, 47, 46]
bebek = [61, 63, 64, 62, 66, 68]

# Plot
plt.figure(figsize=(10, 6))

# Garis untuk tiap jenis daging
plt.plot(bulan, sapi, label='Daging Sapi', color='red', linewidth=2.5)
plt.plot(bulan, ayam, label='Daging Ayam', color='blue', linewidth=2.5)
plt.plot(bulan, kambing, label='Daging Kambing', color='green', linewidth=2.5)
plt.plot(bulan, ikan, label='Daging Ikan', color='orange', linewidth=2.5)
plt.plot(bulan, bebek, label='Daging Bebek', color='purple', linewidth=2.5)

# Label sumbu
plt.xlabel('', fontsize=14)
plt.ylabel('Harga per kg (ribu rupiah)', fontsize=14)

# Grid abu-abu kotak-kotak
plt.grid(True, which='both', linestyle='--', color='gray', linewidth=0.7, alpha=0.6)

# Perbesar font sumbu
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)

# Legend garis
plt.legend(fontsize=13)

# Rapi tanpa judul
plt.tight_layout()
plt.show()

plt.grid(True, axis='y', linestyle='--', color='gray', linewidth=0.7, alpha=0.6)